[build]
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "airtable", "serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/airtable/:splat"
  status = 200
  force = true
